name: Deploy HAT Scala Client

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sbt clean, compile and test
        run: |
          export PATH=$PATH:$HOME/.local/bin
          sbt clean
          sbt compile
          sbt test:compile
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}